services:
  backend:
    build: ./backend
    #Mounts the hosts docker socket into the backend container for code execution (does theoretically grants root-equivalent control if the backend is compromised)
    #Hinges on configuring runsc environments for the hosts docker daemon  
    environment:
      - DOCKER_RUNTIME=runsc #not available on macos
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - backend/.env

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend

  caddy:
      image: caddy:2-alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - frontend
        - backend
      restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: